using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ckknight.ProjectEuler.Collections;

namespace Ckknight.ProjectEuler.Problems
{
    [Problem(2,
        @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        Find the sum of all the even-valued terms in the sequence which do not exceed four million.")]
    public class Problem002 : BaseProblem
    {
        public override object CalculateResult()
        {
            return new FibonacciSequence<long>(1, 1, (a, b) => a + b)
                .TakeWhile(x => x < 4000000)
                .Where(x => (x & 1) == 0)
                .Sum();
        }
    }
}
